name: 'Register package'
description: 'Register package at repository specified as input.local_registry'
author: 'Lukas Grunwald'

inputs:
  local_registry:
    description: 'URL (SSH/Https) to local_registry to be updated by the action'
    required: true
    default: ''
  ssh_keys:
    description: 'SSH Keys for accessing the repos and pushing to registry.'
    required: true
    default: ''


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.8.0 # Add private deploy key to ssh agend
      with:
          ssh-private-key: ${{ inputs.ssh_keys }}
    - uses: julia-actions/setup-julia@latest
      with:
        version: '1'
        arch: x64
    - run: echo "Hello World"
      shell: bash