name: 'Register package'
description: 'Register package at repository specified as input.localregistry'
author: 'Lukas Grunwald'

inputs:
  localregistry:
    description: 'URL (SSH/Https) to local registry to be updated by the action'
    required: true
  ssh_keys:
    description: 'SSH key(s) for accessing the repos and pushing to local registry. Multiple keys by using the pipe |'
    required: true

runs:
  using: 'composite'
  steps:
    # Setup git environment
    - uses: actions/checkout@v4
    - run: | # Git credentials
        git config --global user.name "${{ github.actor }}@RegisterAction"
        git config --global user.email "Register-Action@noreply.github.com"
      shell: bash
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ inputs.ssh_keys }}    

    # Print the current actor
    - run: echo "${{ github.actor }}@RegisterAction"
      shell: bash

    # Setup julia
    - uses: julia-actions/setup-julia@latest
      with:
        version: '1'
        arch: x64
    - uses: julia-actions/cache@v1
      with:
        cache-registries: true

    # Run Local Registrator action 
    - run: julia --color=yes ${{ github.action_path }}/src/ci_register.jl ${{ inputs.localregistry }}
      shell: bash